site_name: Test
nav:
    - Home: README.md
    - Authentication and Authorization: Authentication and Authorization.md
theme: 
  name: 'material'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

# Google Analytics
google_analytics:
  - 'UA-137548591-1'
  - 'auto'
