site_name: Netbrain REST API Documentation
nav:
    - Home: README.md
    - Authentication and Authorization: Authentication and Authorization.md
theme: 
  name: 'material'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

